Vector tests
Lobotuerk/cppl1_q12020 pull request #9
Opened 2020-04-20 12:41 UTC by Lobotuerk

Vector tests finished

2020-04-20 18:20 UTC, glpuga requested changes
Good work!

2020-04-20 18:20 UTC, glpuga commented on course/test/src/vector3_TEST.cc
> +    const Vector3 p{1., 2., 3.};
Are we testing the default constructor `Vector3()`  anywhere?

2020-04-20 18:20 UTC, glpuga commented on course/test/src/vector3_TEST.cc
> +    r += q;
Please add tests for the return value of these with-assignment operators.

2020-04-20 18:20 UTC, glpuga commented on course/test/src/vector3_TEST.cc
> +    EXPECT_EQ(p.y(), 2.);
We need to test also the non-const versions of these getters.

2020-04-20 18:20 UTC, glpuga commented on course/test/src/vector3_TEST.cc
> +    EXPECT_TRUE(r != q);
I think we are not testing the `operator!=(const std::initializer _list &)` operator.

2020-04-20 18:20 UTC, glpuga commented on course/test/src/vector3_TEST.cc
> +    EXPECT_EQ(p[1], 2.);
We need to test also the non-const versions of this operator.

2020-04-20 18:20 UTC, glpuga commented on course/test/src/vector3_TEST.cc
> +    EXPECT_EQ(p[2], 3.);
Please add tests for the out-of-range case.

2020-04-20 18:20 UTC, glpuga commented on course/test/src/vector3_TEST.cc
> +    t.x() = 1.;
We need to test all three of these setters.

2020-04-20 18:20 UTC, glpuga commented on course/test/src/vector3_TEST.cc
> +    t[1] = 2.;
Test also the out-of-range case.

2020-04-20 18:20 UTC, glpuga commented on course/test/src/vector3_TEST.cc
> +    EXPECT_NEAR(Vector3::kUnitY.dot(Vector3::kUnitZ), 0., kTolerance);
If `Vector3::dot()` were just a `return 0.0;` we would pass all these tests. Please add tests for cases that result in non-zero values.

2020-04-22 21:04 UTC, Lobotuerk commented on course/test/src/vector3_TEST.cc
> +    const Vector3 p{1., 2., 3.};
Line 81, is that not testing the default constructor?

2020-04-27 01:56 UTC, glpuga approved these changes
Great work! LGTM

2020-04-27 01:56 UTC, glpuga commented
Approved, please squash and merge!

2020-04-27 12:21 UTC, merged